title: Trânsito ao Vivo
email: transitoaovivo.contato@gmail.com
description: Acompanhe o trânsito em tempo real com câmeras ao vivo em diversas cidades do Brasil
baseurl: ""
url: "https://transitoaovivo.com"
plugins:
  - jekyll-redirect-from
  - jekyll-sitemap
include: ["assets/data"]
keep_files: ["assets/data"]