# .github/workflows/atualizar-trafego.yml

name: Atualizar Dados de Tráfego

on:
  workflow_dispatch: # Permite acionamento manual
  schedule:
    - cron: '*/5 * * * *' # Executa a cada 5 minutos

jobs:
  atualizar_dados:
    runs-on: ubuntu-latest
    permissions:
      contents: write # ESSENCIAL: Permite que o Action escreva no repositório

    steps:
      - name: Checkout do Repositório
        uses: actions/checkout@v4

      # Certifica-se de que a pasta de destino para os JSONs exista
      - name: Criar Pasta de Destino para Dados JSON
        run: |
          mkdir -p assets/_data # Cria o diretório se não existir. -p significa "parents" para criar subpastas se necessário.

      - name: Gerar Dados de Tráfego de Teste (CET-SP)
        run: |
          echo '{"total": 0, "regioes": {"norte": 0, "oeste": 0, "centro": 0, "leste": 0, "sul": 0}, "dataHora": "Gerado pelo Robô em ${{ github.event.repository.pushed_at }}", "runNumber": ${{ github.run_number }}, "teste_cet": true}' | tee assets/data/trafego_cetsp.json
        shell: bash # Garante que este comando é executado em bash

      - name: Gerar Dados de Tráfego de Teste (Artesp)
        run: |
          echo '{"rodovias": [], "dataHora": "Gerado pelo Robô em ${{ github.event.repository.pushed_at }}", "runNumber": ${{ github.run_number }}, "teste_artesp": true}' | tee assets/data/trafego_artesp.json
        shell: bash # Garante que este comando é executado em bash

      - name: Commit e Push dos Dados Atualizados
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          
          # Adicionar todos os arquivos JSON na pasta assets/_data
          git add assets/data/*.json 
          
          # Verificar se há alterações para commitar
          if git diff --quiet --cached; then
            echo "Nenhuma alteração detectada para commitar. Ignorando commit."
          else
            git commit -m "Atualizar dados de tráfego (automatizado)"
            git push origin main
            echo "Dados de tráfego comitados e enviados com sucesso."
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}